---

- name: 'openstack-repo'
  src: 'abelboldu.openstack-repo'

- name: 'geerlingguy.java'
  src: 'geerlingguy.java'

- name: 'mysql'
  src: 'geerlingguy.mysql'

- src: 'https://github.com/openstack-ansible-galaxy/rabbitmq.git'

- src: 'https://github.com/openstack-ansible-galaxy/openstack-keystone.git'

- src: 'https://github.com/openstack-ansible-galaxy/openstack-glance.git'

- src: 'https://github.com/openstack-ansible-galaxy/openstack-nova-compute.git'

- src: 'https://github.com/openstack-ansible-galaxy/openstack-nova-controller.git'

- src: 'https://github.com/openstack-ansible-galaxy/openstack-neutron-controller.git'

- src: 'https://github.com/openstack-ansible-galaxy/openstack-horizon.git'

- name: 'midonet-repo'
  src: 'https://github.com/midonet/ansible-midonet-repo.git'

- name: 'zookeeper'
  src: 'https://github.com/midonet/ansible-zookeeper.git'

- name: 'cassandra'
  src: 'https://github.com/midonet/ansible-cassandra.git'

- name: 'elasticsearch'
  src: 'https://github.com/midonet/ansible-elasticsearch.git'

- name: 'logstash'
  src: 'https://github.com/midonet/ansible-logstash.git'

- name: 'midonet-cluster'
  src: 'https://github.com/midonet/ansible-midonet-cluster.git'

- name: 'midonet-agent'
  src: 'https://github.com/midonet/ansible-midonet-agent.git'

- name: 'midonet-insights-analytics'
  src: 'https://github.com/midonet/ansible-midonet-insights-analytics.git'

- name: 'midonet-manager'
  src: 'https://github.com/midonet/ansible-midonet-manager.git'
