---

- name: 'openstack-repo'
  src: 'abelboldu.openstack-repo'

- name: 'geerlingguy.java'
  src: 'geerlingguy.java'

- name: 'mysql'
  src: 'geerlingguy.mysql'

- src: 'https://github.com/openstack-ansible-galaxy/rabbitmq.git'

- src: 'https://github.com/openstack-ansible-galaxy/openstack-keystone.git'

- src: 'https://github.com/openstack-ansible-galaxy/openstack-glance.git'

- src: 'https://github.com/openstack-ansible-galaxy/openstack-nova-compute.git'

- src: 'https://github.com/openstack-ansible-galaxy/openstack-nova-controller.git'

- src: 'https://github.com/openstack-ansible-galaxy/openstack-neutron-controller.git'

- src: 'https://github.com/openstack-ansible-galaxy/openstack-horizon.git'

- name: 'midonet-repo'
  src: 'https://github.com/ryo-tagami/ansible-midonet-repo'
  version: 'insights'

- name: 'zookeeper'
  src: 'https://github.com/ryo-tagami/ansible-zookeeper'
  version: 'insights'

- name: 'cassandra'
  src: 'https://github.com/ryo-tagami/ansible-cassandra'
  version: 'insights'

- name: 'elasticsearch'
  src: 'https://github.com/ryo-tagami/ansible-elasticsearch'
  version: 'insights'

- name: 'logstash'
  src: 'https://github.com/ryo-tagami/ansible-logstash'
  version: 'insights'

- name: 'midonet-cluster'
  src: 'https://github.com/ryo-tagami/ansible-midonet-cluster'
  version: 'insights'

- name: 'midonet-agent'
  src: 'https://github.com/ryo-tagami/ansible-midonet-agent'
  version: 'insights'

- name: 'midonet-insights-analytics'
  src: 'https://github.com/ryo-tagami/ansible-midonet-insights-analytics'
  version: 'wip'

- name: 'midonet-manager'
  src: 'https://github.com/ryo-tagami/ansible-midonet-manager'
  version: 'insights'
