---

- include: common.yml

- hosts: all
  become: True

  pre_tasks:
    - set_fact:
        midonet_repo_mem_enabled: True
        midonet_repo_mem_username: '{{ lookup("env", "MEM_USERNAME") }}'
        midonet_repo_mem_password: '{{ lookup("env", "MEM_PASSWORD") }}'
        midonet_cluster_mem_enabled: True
        midonet_agent_mem_enabled: True
      when: '{{ lookup("env", "MEM_ENABLED")|default(False) }}'

    - set_fact:
        mysql_daemon: 'mysql'
        mysql_log_error: '/var/log/mysql/error.log'
        mysql_pid_file: '/var/run/mysqld/mysqld.pid'
        mysql_packages:
          - 'mariadb-client'
          - 'mariadb-server'
          - 'python-mysqldb'
      when: ansible_os_family == 'Debian'

    - set_fact:
        mysql_daemon: 'mariadb'
        mysql_socket: '/var/lib/mysql/mysql.sock'
        mysql_log_error: '/var/log/mariadb/mariadb.log'
        mysql_syslog_tag: 'mariadb'
        mysql_pid_file: '/var/run/mariadb/mariadb.pid'
      when: ansible_os_family == 'RedHat'

  roles:
    - midonet-repo
    - mysql
    - rabbitmq

    - role: openstack-keystone
      keystone_run_sanity_check: True

    - openstack-glance
    - openstack-nova-controller
    - openstack-nova-compute
    - openstack-neutron-controller
    - openstack-horizon

    - role: zookeeper
      zookeeper_hosts:
        - '{{ inventory_hostname }}'

    - role: cassandra
      cassandra_hosts:
        - '{{ inventory_hostname }}'
      cassandra_max_heap_size: '512M'
      cassandra_heap_newsize: '256M'

    - role: elasticsearch

    - role: logstash
      logstash_listen_port_lumberjack: 4999

    - role: midonet-cluster
      zookeeper_hosts:
        - '{{ inventory_hostname }}'
      cassandra_hosts:
        - '{{ inventory_hostname }}'
      midonet_cluster_max_heap_size: '512M'
      midonet_cluster_heap_newsize: '256M'
      midonet_cluster_metadata_host: '{{ ansible_default_ipv4.address }}'
      midonet_cluster_flow_tracing_auth_ssl_enabled: False

    - role: midonet-agent
      zookeeper_hosts:
        - '{{ inventory_hostname }}'
      cassandra_hosts:
        - '{{ inventory_hostname }}'
      midonet_agent_max_heap_size: '512M'

    - role: midonet-insights-analytics
      zookeeper_hosts:
        - '{{ inventory_hostname }}'
      cassandra_hosts:
        - '{{ inventory_hostname }}'
      midonet_insights_analytics_calliope_auth_ssl_enabled: False

    - role: midonet-manager
      ssl_enabled: False
      midonet_api_hostname: '{{ public_ip }}'
      login_hostname: '{{ public_ip }}'
