---

- include: common.yml

- hosts: all
  become: True

  pre_tasks:
    - set_fact:
        mysql_daemon: 'mysql'
        mysql_log_error: '/var/log/mysql/error.log'
        mysql_pid_file: '/var/run/mysqld/mysqld.pid'
        mysql_packages:
          - 'mariadb-client'
          - 'mariadb-server'
          - 'python-mysqldb'
      when: ansible_os_family == 'Debian'

    - set_fact:
        mysql_daemon: 'mariadb'
        mysql_socket: '/var/lib/mysql/mysql.sock'
        mysql_log_error: '/var/log/mariadb/mariadb.log'
        mysql_syslog_tag: 'mariadb'
        mysql_pid_file: '/var/run/mariadb/mariadb.pid'
      when: ansible_os_family == 'RedHat'

  roles:
    - midonet-repo
    - mysql
    - rabbitmq

    - role: openstack-keystone
      keystone_run_sanity_check: True

    - openstack-glance
    - openstack-nova-controller
    - openstack-nova-compute
    - openstack-neutron-controller
    - openstack-horizon

    - role: zookeeper
      zookeeper_hosts:
        - '{{ inventory_hostname }}'

    - role: cassandra
      cassandra_hosts:
        - '{{ inventory_hostname }}'

    - role: midonet-cluster
      zookeeper_hosts:
        - '{{ inventory_hostname }}'
      cassandra_hosts:
        - '{{ inventory_hostname }}'
      midonet_cluster_max_heap_size: '512M'

    - role: midonet-agent
      zookeeper_hosts:
        - '{{ inventory_hostname }}'
      cassandra_hosts:
        - '{{ inventory_hostname }}'
      midonet_agent_max_heap_size: '512M'
